option('nls', type : 'boolean', value : true, description : 'Native language support')
option('exif', type : 'feature', value : 'auto', description : 'EXIF viewer and EXIF orientation (system libexif)')
option('splash', type : 'boolean', value : true, description : 'Splash window on startup')
option('jpeg', type : 'feature', value : 'auto', description : 'libjpeg based JPEG loader plugin')
option('mng', type : 'feature', value : 'auto', description : 'MNG loader plugin (libmng)')
option('svg', type : 'feature', value : 'auto', description : 'SVG loader plugin (librsvg)')
option('wmf', type : 'feature', value : 'auto', description : 'WMF loader plugin (libwmf)')
option('mplayer', type : 'boolean', value : true, description : 'MPlayer movie plugin (runs the mplayer program)')
option('libarchive', type : 'feature', value : 'auto', description : 'archive support (zip, rar, 7z, lha, tar, ...) with libarchive')
option('gstreamer', type : 'feature', value : 'auto', description : 'GStreamer movie plugin (GStreamer >= 1.16)')
option('xine', type : 'feature', value : 'auto', description : 'xine movie plugin (libxine >= 1.2)')
